/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TunniplaanRouteImport } from './routes/tunniplaan'
import { Route as EditRouteImport } from './routes/edit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageSlugRouteImport } from './routes/page.$slug'
import { Route as CategoryIdRouteImport } from './routes/category.$id'

const TunniplaanRoute = TunniplaanRouteImport.update({
  id: '/tunniplaan',
  path: '/tunniplaan',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSlugRoute = PageSlugRouteImport.update({
  id: '/page/$slug',
  path: '/page/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/tunniplaan': typeof TunniplaanRoute
  '/category/$id': typeof CategoryIdRoute
  '/page/$slug': typeof PageSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/tunniplaan': typeof TunniplaanRoute
  '/category/$id': typeof CategoryIdRoute
  '/page/$slug': typeof PageSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/tunniplaan': typeof TunniplaanRoute
  '/category/$id': typeof CategoryIdRoute
  '/page/$slug': typeof PageSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/edit' | '/tunniplaan' | '/category/$id' | '/page/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/edit' | '/tunniplaan' | '/category/$id' | '/page/$slug'
  id:
    | '__root__'
    | '/'
    | '/edit'
    | '/tunniplaan'
    | '/category/$id'
    | '/page/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditRoute: typeof EditRoute
  TunniplaanRoute: typeof TunniplaanRoute
  CategoryIdRoute: typeof CategoryIdRoute
  PageSlugRoute: typeof PageSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tunniplaan': {
      id: '/tunniplaan'
      path: '/tunniplaan'
      fullPath: '/tunniplaan'
      preLoaderRoute: typeof TunniplaanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$slug': {
      id: '/page/$slug'
      path: '/page/$slug'
      fullPath: '/page/$slug'
      preLoaderRoute: typeof PageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditRoute: EditRoute,
  TunniplaanRoute: TunniplaanRoute,
  CategoryIdRoute: CategoryIdRoute,
  PageSlugRoute: PageSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
